### ISSUE TITLE
Support for parameter "traffic_model"

### ISSUE THREAD

**Issue by ivanram** [akexorcist/GoogleDirectionLibrary#75]
Hi, I found your library extremely useful and have been using it for some time.

Do you think it would be possible to add support for the parameter "traffic_model"

I feel like Google is too optimistic with the traffic in Bangkok so I would like to be able to set it as "pessimistic"

Or maybe you could allow to enter raw parameters, so it is way more flexible or something.

**Comment by akexorcist** [comment]
Added in 1.2.1
