### ISSUE TITLE
dptopx got nulled exception in v1.1.1

### ISSUE THREAD

**Issue by khizar1556** [akexorcist/GoogleDirectionLibrary#76]
it exist again and again please resolve this issue i am using 1.1.1 version of your liberary problem is still exist

`com.akexorcist.googledirection.util.DirectionConverter.dpToPx (DirectionConverter.java:101)`

`Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference` 
please resolve this issue asap

**Comment by akexorcist** [comment]
Because you passed the context into `createPolyline(...)` with null.

**Comment by akexorcist** [comment]
I close this issue because there's no response for a while. Feel free to reopen it if you still have an issue about this.
