### ISSUE TITLE
After add waypoint with .and, it stop draw polyline after 1st waypoint in route  

### ISSUE THREAD

**Issue by saadbzu** [akexorcist/GoogleDirectionLibrary#77]

**Comment by akexorcist** [comment]
Could you please provide the latitude/longitude for the direction that I can reproduce your problem?

**Comment by mishragashish** [comment]
Facing same issue. Its not drawing polyline after first way point.

**Comment by mishragashish** [comment]
From lat/lng: (26.5507785,80.481009)
Ways Point lat/lng: (26.552678,80.479401),lat/lng: (26.536169,80.483978)
To lat/lng: (26.544338,80.4904724)

**Comment by akexorcist** [comment]
@mishragashish  I tested on sample project with your location. It's work fine

```kotlin
val start = LatLng(26.5507785, 80.481009)
val waypoint1 = LatLng(26.552678,80.479401)
val waypoint2 = LatLng(26.536169,80.483978)
val to = LatLng(26.544338,80.4904724)
GoogleDirection.withServerKey(serverKey)
    .from(start)
    .and(waypoint1)
    .and(waypoint2)
    .to(to)
    .transportMode(TransportMode.DRIVING)
    .execute(
        onDirectionSuccess = { direction -> onDirectionSuccess(direction) },
        onDirectionFailure = { t -> onDirectionFailure(t) }
    )
```

![image](https://user-images.githubusercontent.com/1949576/102515162-fa778480-40bf-11eb-8859-7e990cb96c4d.png)

Please tell me more if there's incorrect in my test.

**Comment by akexorcist** [comment]
I close this issue because there's no response for a while. Feel free to reopen it if you still have an issue about this.
